### ISSUE TITLE
Pokémon parece não estar com imagem no nearby

### ISSUE THREAD

**Issue by NeukommRox** [ArthurSDev/PoGoIncense#2]
Device info
------------------
- Phone type: (Lumia 635 (512ram))
- App version: (1.0.29 não oficial)

Steps to reproduce
----------------
Encontre o pokémon em questão.

Actual behavior
-----------------
Ao aparecer o pokémon no nearby não aparece uma imagem associada.

Expected behavior
---------------
Que o pokémon apareça no nearby.

Other information
---------------
Não sei qual pokémon é, não consegui encontrá-lo.
Foto:
[IMG]http://i68.tinypic.com/2mq5d2w.png](url)

**Comment by ArthurSDev** [comment]
É um bug do próprio Pokemon GO, estava no oficial, e ai apareceu no nearby um quadradinho branco.
